<script lang="ts">
	import { marked } from '$lib/common/marked';
	import Experience from '$lib/components/section/Experience.svelte';
	import Hobby from '$lib/components/section/Hobby.svelte';
	import OpenSourceContribution from '$lib/components/section/OpenSourceContribution.svelte';
	import Projects from '$lib/components/section/Projects/Projects.svelte';
	import Section from '$lib/components/section/Section.svelte';
	import type { Experience as ExperienceType, Project } from '$lib/types';
	import Icon from '@iconify/svelte';
	import cx from 'classnames';

	import Animated from '$lib/components/Animated.svelte';
	import Copyable from '$lib/components/utils/Copyable.svelte';
	import { convertRemToPixels, isInViewport } from '$lib/utils';
	import { onMount } from 'svelte';

	const sections = [
		{
			id: 'about-me',
			label: 'About Me'
		},
		{
			id: 'experience',
			label: 'Experience'
		},
		{
			id: 'projects',
			label: 'Projects'
		},
		{
			id: 'open-source-contributions',
			label: 'Open-Source Contributions'
		},
		{
			id: 'hobbies',
			label: 'Hobbies'
		},
		{
			id: 'resume',
			label: 'Résumé'
		},
		{
			id: 'contact-me',
			label: 'Contact Me'
		}
	];

	const EMAIL = 'robindimasin.social@outlook.com';

	const links = [
		{
			id: 'github',
			url: 'https://github.com/RobinPH',
			target: '_blank',
			tooltip: 'GitHub: RobinPH',
			icon: 'fa6-brands:github-square'
		},
		{
			id: 'linkedin',
			url: 'https://www.linkedin.com/in/robin-dimasin/',
			target: '_blank',
			tooltip: 'LinkedIn: robin-dimasin',
			icon: 'fa6-brands:linkedin'
		},
		{
			id: 'upwork',
			url: 'https://www.upwork.com/freelancers/~019df91773db7c6467',
			tooltip: 'Upwork: Robin D.',
			target: '_blank',
			icon: 'fa6-brands:square-upwork'
		},
		{
			id: 'email',
			url: `mailto:${EMAIL}`,
			tooltip: EMAIL,
			target: '_self',
			copy: EMAIL,
			icon: 'icon-park-solid:maill-one'
		},
		{
			id: 'phone',
			url: 'tel:639764834569',
			tooltip: 'Phone: +63 (976) 483 4569',
			target: '_self',
			copy: '+639764834569',
			icon: 'icon-park-solid:phone-two'
		}
	];

	const experiences: ExperienceType[] = [
	{
			title: 'Junior Software Engineer',
			roles: ['Full-time'],
			company: {
				name: 'Freelancer.com',
				url: 'https://www.linkedin.com/company/freelancer-com'
			},
			description: '',
			url: 'https://www.linkedin.com/company/freelancer-com',
			links: [],
			technologies: [],
			duration: {
				start: new Date(2024, 9),
				end: null
			}
		},
		{
			title: 'Web Developer',
			roles: ['Intern'],
			company: {
				name: 'OneQuantum Philippines',
				url: 'https://www.linkedin.com/company/onequantum-ph'
			},
			description:
				'Responsible for developing web products, including key landing pages, and Learning Management System',
			url: 'https://www.linkedin.com/company/onequantum-ph',
			links: [],
			technologies: [],
			duration: {
				start: new Date(2024, 6, 13),
				end: new Date(2024, 9),
			}
		},
		{
			title: 'Python & Fullstack Developer',
			roles: ['Freelance'],
			company: null,
			description:
				'Provides different services such as **Web Scraping**, **Fullstack Development**, **Browser Automation using Selenium/Puppeteer**, **Python Scripting**, **Task Automation**, and **Chrome Extension Development**.',
			url: 'https://www.upwork.com/freelancers/~019df91773db7c6467',
			links: [
				{
					label: 'My Upwork Profile',
					url: 'https://www.upwork.com/freelancers/~019df91773db7c6467'
				}
			],
			technologies: [
				'Python',
				'JavaScript',
				'React',
				'HTML & CSS',
				'Selenium',
				'Puppeteer',
				'Laravel'
			],
			duration: {
				start: new Date(2022, 8, 20),
				end: new Date(2024, 9),
			}
		},
		{
			title: 'System Analyst',
			roles: ['Intern', 'Team Lead'],
			company: {
				name: 'Pixel8 Web Solutions & Consultancy Inc.',
				url: 'https://www.linkedin.com/company/pixel8websolutions/'
			},
			description:
				'**Analyzed** and **designed** system flows using **Figma**. **Team Leader** in the second half of the duration of the internship.',
			url: 'https://www.linkedin.com/company/pixel8websolutions/',
			links: [],
			technologies: ['Figma'],
			duration: {
				start: new Date(2023, 7, 21),
				end: new Date(2023, 8, 27)
			}
		}
	];

	const projects: Project[] = [
		{
			title: 'Behind the Words',
			description:
				'**Thesis paper** about detecting english essays generated by LLM such as ChatGPT. Trained an **XGBoost** model boosted by **Convolutional Neural Network (CNN)**. Achieved **98.69% accuracy** in detecting LLM-generated english essays.',
			url: 'https://behind-the-words.robindimasin.com/',
			links: [
				{
					label: 'Website',
					url: 'https://behind-the-words.robindimasin.com/'
				},
				{
					label: 'GitHub',
					url: 'https://github.com/RobinPH/behind-the-words'
				},
				{
					label: 'Paper',
					url: 'https://bit.ly/behind-the-words-paper'
				},
				{
					label: 'LinkedIn',
					url: 'https://lnkd.in/gasPjiG7'
				}
			],
			github: {
				owner: 'RobinPH',
				repo: 'behind-the-words'
			},
			thumbnail: '/images/projects/behind-the-words/thumbnail.png',
			technologies: [
				'AI/ML',
				'Python',
				'LLM',
				'XGBoost',
				'CNN',
				'TensorFlow',
				'Flask',
				'SvelteKit'
			],
			duration: {
				start: new Date(2023, 2),
				end: new Date(2024, 0)
			},
			featured: true
		},
		{
			title: 'Swiss',
			description:
				'A **code parser** based around the idea of Finite State Machine, Automata, and Regular Expression',
			url: 'https://github.com/RobinPH/swiss',
			links: [
				{
					label: 'GitHub',
					url: 'https://github.com/RobinPH/swiss'
				}
			],
			github: {
				owner: 'RobinPH',
				repo: 'swiss'
			},
			technologies: ['TypeScript', 'NodeJS', 'Jest', 'Unit Testing'],
			thumbnail: '/images/projects/swiss/thumbnail.png',
			duration: {
				start: new Date(2023, 0),
				end: new Date(2023, 1)
			},
			featured: true
		},
		{
			title: 'CodeExecutor',
			description:
				'A **Minecraft server plugin** that enables player to **write, and execute code inside Minecraft** using PistonAPI',
			url: 'https://github.com/RobinPH/CodeExecutor',
			links: [
				{
					label: 'GitHub',
					url: 'https://github.com/RobinPH/CodeExecutor'
				},
				{
					label: 'SpigotMC',
					url: 'https://www.spigotmc.org/resources/codeexecutor.88710/'
				}
			],
			github: {
				owner: 'RobinPH',
				repo: 'CodeExecutor'
			},
			technologies: ['Java', 'Spigot API', 'Piston API'],
			thumbnail: '/images/projects/codeexecutor/thumbnail.png',
			duration: {
				start: new Date(2021, 1),
				end: new Date(2021, 1)
			},
			featured: true
		},
		{
			title: "Harvard's CS50 2020",
			description:
				"**Completed three courses**, including the required projects, from **Harvard's CS50 2020**",
			links: [
				{
					label: 'CS50x',
					url: 'https://certificates.cs50.io/9bc1e1fa-a4ee-47a1-a47f-001f6c9e15fb'
				},
				{
					label: 'CS50 Web',
					url: 'https://certificates.cs50.io/8c955b50-f63f-4914-a942-4a0c5ebb441d'
				},
				{
					label: 'CS50 AI',
					url: 'https://certificates.cs50.io/51378dd6-9b03-4971-b4a6-eaad23548693'
				}
			],
			technologies: ['C', 'Python', 'SQL', 'Web Dev', 'Django', 'JavaScript', 'Git', 'AI'],
			thumbnail: '/images/projects/cs50/thumbnail.png',
			duration: {
				start: new Date(2020, 3, 28),
				end: new Date(2020, 4, 25)
			},
			featured: true
		},
		{
			title: 'AWPAP',
			description:
				'Developed a web platform for **pet adoption**. Experimented with Google, Facebook, and GitHub OAuth',
			url: 'https://github.com/RobinPH/awpap',
			links: [
				{
					label: 'GitHub',
					url: 'https://github.com/RobinPH/awpap'
				}
			],
			github: {
				owner: 'RobinPH',
				repo: 'awpap'
			},
			technologies: ['PHP', 'Laravel', 'Blade', 'Livewire', 'AlpineJS', 'TailwindCSS'],
			duration: {
				start: new Date(2023, 5),
				end: new Date(2023, 6)
			}
		},
		{
			title: 'ShopEase',
			description:
				'Developed an **E-commerce website**. Used Prisma to create database, and introspected it using dotnet CLI for code generation',
			links: [],
			thumbnail: '/images/projects/shopease/thumbnail.png',
			technologies: ['.NET', 'React', 'Prisma', 'TailwindCSS'],
			duration: {
				start: new Date(2023, 1),
				end: new Date(2023, 2)
			}
		},
		{
			title: 'RoeDigits',
			description:
				'Developed a subscription-based web platform that offers basic math courses. Added Progressive Web App (PWA) support, and Search Engine Optimization (SEO)',
			url: 'https://roedigits.vercel.app/',
			links: [
				{
					label: 'GitHub',
					url: 'https://github.com/RobinPH/roedigits'
				}
			],
			github: {
				owner: 'RobinPH',
				repo: 'roedigits'
			},
			thumbnail: '/images/projects/roedigits/thumbnail.png',
			technologies: [
				'SvelteKit',
				'Prisma',
				'SEO',
				'Progressive Web App (PWA)',
				'TailwindCSS',
				'DaisyUI'
			],
			duration: {
				start: new Date(2022, 6),
				end: new Date(2022, 6)
			}
		},
		{
			title: 'Vetreatment: Pet Clinic',
			description:
				'Developed a full-stack web application for managing appointments in pet clinic.',
			url: 'https://vetreatment.vercel.app/',
			links: [
				{
					label: 'GitHub',
					url: 'https://github.com/RobinPH/vet-app'
				}
			],
			github: {
				owner: 'RobinPH',
				repo: 'vet-app'
			},
			technologies: ['React', 'NextJS', 'JavaScript', 'MySQL', 'TailwindCSS', 'DaisyUI'],
			duration: {
				start: new Date(2022, 5),
				end: new Date(2022, 6)
			}
		},
		{
			title: 'Would You Rather Telegram Bot',
			description:
				'Developed a **Telegram Bot** that serves a Would You Rather game inside Telegram Chat. Experimented with Heroku, MongoDB, and Telegram Bot API.',
			url: 'https://github.com/RobinPH/would-you-rather-telegram-bot',
			links: [
				{
					label: 'GitHub',
					url: 'https://github.com/RobinPH/would-you-rather-telegram-bot'
				}
			],
			github: {
				owner: 'RobinPH',
				repo: 'would-you-rather-telegram-bot'
			},
			technologies: ['TypeScript', 'Telegram API', 'MongoDB', 'Heroku'],
			duration: {
				start: new Date(2020, 5),
				end: new Date(2020, 5)
			}
		}
	];

	const openSourceContributions = [
		{
			github: {
				website: 'www.manim.community',
				name: 'manim',
				owner: 'ManimCommunity',
				repo: 'manim',
				description: 'A community-maintained Python framework for creating mathematical animations.'
			},
			contributions: [
				{
					id: 3428,
					title:
						'Added **grid_lines** attribute to **Rectangle** to add individual styling to the grid lines',
					date: new Date(2023, 9, 31)
				}
			]
		}
	];

	const hobbies = [
		{
			title: 'Competitive Programming',
			description:
				"Participated in numerous competitive programming contests. **UP ACM's Algolympics finalist** in year 2021 to 2023, and **ranked 4th** in year 2021, and 2023.",
			links: [
				{
					label: 'Codeforces',
					url: 'https://codeforces.com/profile/RobinPH'
				},
				{
					label: 'Algolympics',
					url: 'https://algolympics.upacm.net/'
				},
				{
					label: 'AtCoder',
					url: 'https://atcoder.jp/users/RobinPH'
				},
				{
					label: 'CodeChef',
					url: 'https://www.codechef.com/users/robinph'
				},
				{
					label: 'LeetCode',
					url: 'https://leetcode.com/u/RobinPH/'
				}
			]
		}
	];

	let viewingSection: string | null = null;

	let sideMenuToggle: HTMLInputElement | null = null;

	onMount(() => {
		const setViewingSection = (event?: Event) => {
			event?.preventDefault();

			const hero = document.getElementById('hero');

			if (hero) {
				if (getComputedStyle(hero, null).display === 'flex' && isInViewport(hero)) {
					viewingSection = null;
					// @ts-ignore
					// history.pushState({}, null, ' ');
					return;
				}
			}

			for (const { id } of sections) {
				const sectionHeader = document.getElementById(id)?.querySelector('h1');

				if (sectionHeader) {
					if (isInViewport(sectionHeader)) {
						viewingSection = id;
						// @ts-ignore
						// history.pushState({}, null, `#${id}`);
						break;
					}
				}
			}
		};

		const showNavigationBar = () => {
			const navigationBar = document.getElementById('navigation-bar');
			if (navigationBar) {
				if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
					navigationBar.style.top = '0';
				} else {
					navigationBar.style.top = '-100%';
				}
			}
		};

		if (window.location.hash) {
			window.scrollTo({
				top: document.body.scrollTop + convertRemToPixels(5)
			});
		}

		window.addEventListener('scroll', setViewingSection);
		window.addEventListener('scroll', showNavigationBar);

		setViewingSection();
		showNavigationBar();

		return () => {
			window.removeEventListener('scroll', setViewingSection);
			window.removeEventListener('scroll', showNavigationBar);
		};
	});
</script>

<svelte:head>
	<title>Robin Dimasin | Junior Software Engineer</title>

	<meta
		name="description"
		content="Robin Dimasin, Junior Software Engineer at Freelancer.com"
	/>
</svelte:head>

<div
	class="fixed left-0 z-[60] transition-all duration-300 -top-full navbar bg-neutral lg:hidden"
	id="navigation-bar"
>
	<div class="flex-none">
		<label for="sidemenu" class="text-xl btn btn-ghost drawer-button">
			<Icon icon="iconamoon:menu-burger-horizontal-bold" />
		</label>
	</div>
	<div class="flex-1">
		<span class="text-xl">ROBIN DIMASIN</span>
	</div>
</div>

<div class="drawer">
	<input id="sidemenu" type="checkbox" class="drawer-toggle" bind:this={sideMenuToggle} />
	<div class="z-[70] drawer-side">
		<label for="sidemenu" aria-label="close sidebar" class="drawer-overlay"></label>
		<div class="flex flex-col justify-between h-full p-8 bg-base-200">
			<nav class="flex flex-col h-full gap-4 overflow-y-auto text-xs xl:pl-10">
				{#each sections as section, i}
					<a
						href="#{section.id}"
						class={cx(
							'font-medium [&>*]:hover:text-info [&>*]:hover:font-bold flex items-center gap-2 [&>*]:hover:block w-fit',
							viewingSection === section.id && '[&>*]:text-info [&>*]:font-bold [&>*]:block'
						)}
						on:click={() => {
							if (sideMenuToggle) {
								sideMenuToggle.checked = false;
							}
						}}
					>
						<Icon class="hidden icon text-info" icon="bxs:right-arrow" />
						<span class="text-info">{i.toString().padStart(2, '0')}.</span>
						<span class="text-gray-400">{section.label}</span></a
					>
				{/each}
			</nav>
			<div class="flex gap-2">
				{#each links as link, i}
					<a href={link.url} target={link.target ?? '_blank'} aria-label={link.tooltip}>
						<Icon
							icon={link.icon}
							class="size-6 hover:text-info hover:-translate-y-0.5 duration-150"
						/>
					</a>
				{/each}
			</div>
		</div>
	</div>
</div>

<main class="flex pl-0 pr-8 md:px-12 lg:px-20 xl:px-52 max-w-[100rem] justify-center m-auto">
	<footer class="sticky top-0 flex flex-col justify-end h-[100dvh] px-1 lg:hidden">
		{#each links as link, i}
			<Animated animations={[{ type: 'fade-in' }, { type: 'fly-left' }]} delay={125 + 125 * i}>
				<a href={link.url} target={link.target ?? '_blank'} aria-label={link.tooltip}>
					<div class="tooltip tooltip-left" data-tip={link.tooltip}>
						<Icon
							icon={link.icon}
							class="size-6 hover:text-info hover:-translate-y-0.5 duration-150"
						/>
					</div>
				</a>
			</Animated>
		{/each}
	</footer>
	<div
		class="sticky top-0 flex-col hidden w-full h-screen gap-8 py-20 pr-4 xl:gap-16 xl:pr-10 lg:flex"
	>
		<header>
			<Animated animations={[{ type: 'fade-in' }, { type: 'fly-left' }]}>
				<p class="text-gray-400">Hello, my name is</p>
				<h1 class="text-4xl font-black uppercase md:text-5xl 2xl:text-6xl text-info">
					Robin Dimasin
				</h1>
				<h2 class="text-gray-400">
					<span class="font-semibold text-primary-content">Junior Software Engineer</span>
					at
					<span class="font-semibold text-primary-content"><a class="link" href="https://www.freelancer.com/" target="_blank">Freelancer.com</a></span>.
				</h2>
			</Animated>
		</header>

		<nav class="flex flex-col h-full gap-4 pl-4 overflow-y-auto xl:pl-10">
			{#each sections as section, i}
				<Animated animations={[{ type: 'fade-in' }, { type: 'fly-left' }]} delay={125 + 125 * i}>
					<a
						href="#{section.id}"
						class={cx(
							'font-medium [&>*]:hover:text-info [&>*]:hover:font-bold flex items-center gap-2 [&>*]:hover:block w-fit',
							viewingSection === section.id && '[&>*]:text-info [&>*]:font-bold [&>*]:block'
						)}
					>
						<Icon class="hidden icon text-info" icon="bxs:right-arrow" />
						<span class="text-info">{i.toString().padStart(2, '0')}.</span>
						<span class="text-gray-400">{section.label}</span></a
					>
				</Animated>
			{/each}
		</nav>

		<footer class="flex gap-2">
			{#each links as link, i}
				<Animated
					animations={[{ type: 'fade-in' }, { type: 'fly-up' }]}
					delay={125 + sections.length * 125 + 125 * i}
				>
					<div class="relative [&>.copy-btn]:hover:opacity-100 tooltip" data-tip={link.tooltip}>
						<a href={link.url} target={link.target ?? '_blank'} aria-label={link.tooltip}>
							<Icon
								icon={link.icon}
								class="size-8 hover:text-info hover:-translate-y-0.5 duration-150"
							/>
						</a>
						{#if link.copy}
							<div
								class="absolute duration-200 -translate-x-1/2 opacity-0 w-fit copy-btn -bottom-3/4 left-1/2"
							>
								<Copyable text={link.copy}>
									<button class="btn btn-ghost btn-xs">
										<Icon icon="fa6-solid:copy" class="text-white" />
									</button>
								</Copyable>
							</div>
						{/if}
					</div>
				</Animated>
			{/each}
		</footer>
	</div>

	<div
		class="flex flex-col w-full gap-20 pt-8 lg:pt-20 [&>section:last-child]:min-h-screen overflow-x-hidden"
	>
		<Animated animations={[{ type: 'fade-in' }, { type: 'fly-left' }]}>
			<header class="flex flex-col lg:hidden" id="hero">
				<p class="text-xs text-gray-400">Hello, my name is</p>
				<h1 class="text-4xl font-black uppercase text-info">Robin Dimasin</h1>
				<h2 class="text-xs text-gray-400">
					<span class="font-semibold text-primary-content">Junior Software Engineer</span>
					at
					<span class="font-semibold text-primary-content"><a class="link" href="https://www.freelancer.com/" target="_blank">Freelancer.com</a></span>.
				</h2>
			</header>
		</Animated>
		<Section id="about-me" index={0} label="About Me">
			<div class="text-xs text-gray-400">
				{@html marked(
					`I am a **Junior Software Engineer** at **Freelancer.com**.`
				)}
				<br />
				{@html marked(
					`My notable projects include a thesis on detecting LLM-generated essays with **a 98.69% accuracy rate** and developing a Minecraft server plugin. I contribute to open-source projects and have a passion for **competitive programming**, having been a finalist for **4 consecutive years** in UP ACM's Algolympics.`
				)}
				<br />
				{@html marked(
					`**I am always open** to new opportunities and collaborations, and I welcome any chance to connect.`
				)}
			</div>
		</Section>
		<Section id="experience" index={1} label="Experience">
			<div class="flex flex-col gap-6">
				{#each experiences as experience, i (i)}
					<Animated animations={[{ type: 'fade-in' }, { type: 'fly-right' }]} delay={125}>
						<Experience {experience} />
					</Animated>
				{/each}
			</div>
		</Section>
		<Section id="projects" index={2} label="Projects">
			<Projects {projects} show={4} />
		</Section>
		<Section id="open-source-contributions" index={3} label="Open-Source Contributions">
			<div class="flex flex-col gap-4">
				{#each openSourceContributions as openSourceContribution}
					<Animated animations={[{ type: 'fade-in' }, { type: 'fly-right' }]} delay={125}>
						<OpenSourceContribution {openSourceContribution} />
					</Animated>
				{/each}
			</div>
		</Section>
		<Section id="hobbies" index={4} label="Hobbies">
			<div class="flex flex-col gap-6">
				{#each hobbies as hobby}
					<Animated animations={[{ type: 'fade-in' }, { type: 'fly-right' }]} delay={125}>
						<Hobby {hobby} />
					</Animated>
				{/each}
			</div></Section
		>
		<Section id="resume" index={5} label="Résumé">
			<div class="flex flex-col gap-4">
				<iframe
					title="Résumé | Dimasin, Robin Victor D."
					src="/resume.pdf"
					class="w-full h-[75dvh]"
				/>
				<a href="/resume.pdf" target="_blank" class="btn btn-info"
					>View Résumé in New Tab <Icon icon="mingcute:external-link-line" /></a
				>
			</div>
		</Section>
		<Section id="contact-me" index={6} label="Contact Me">
			<div class="flex flex-col gap-4">
				<div class="flex flex-col gap-2 md:gap-0">
					<div class="flex flex-col md:gap-2 md:items-center md:flex-row">
						<h2 class="text-lg font-bold job-title">Let's Connect!</h2>
						<Copyable text={EMAIL}>
							<div
								class="w-full flex items-center gap-2 m-auto text-xs hover:cursor-pointer [&>*]:hover:text-info [&>span]:hover:border-info [&>*]:hover:opacity-100"
							>
								<span class="text-white border-b-2 border-dotted">{EMAIL}</span>
								<Icon icon="fa6-solid:copy" class="duration-300 opacity-0 size-4"></Icon>
							</div>
						</Copyable>
					</div>
					<p class="text-xs text-gray-400">
						I am always open to new opportunities, collaborations, and feedback. Whether you have a
						project in mind, a question, or just want to say hello, I would love to hear from you!
					</p>
				</div>
				<div class="flex flex-col items-center gap-2">
					<div class="w-full tooltip tooltip-bottom" data-tip={EMAIL}>
						<a href={`mailto:${EMAIL}`} class="w-full btn btn-info">Send me an email</a>
					</div>
				</div>
				<div class="flex flex-col gap-2 text-xs text-gray">
					<div>You can also connect with me on:</div>
					<div class="flex flex-col gap-1 ml-4 text-md">
						{#each links.filter((link) => link.id !== 'email') as link}
							<a
								href={link.url}
								target={link.target ?? '_blank'}
								aria-label={link.tooltip}
								class="flex items-center gap-1 duration-150 hover:text-info w-fit"
							>
								<Icon icon={link.icon} class="size-6" />
								<span class="font-bold">{link.tooltip}</span>
							</a>
						{/each}
					</div>
				</div>
			</div>
		</Section>
	</div>
</main>
